### ISSUE TITLE
saving and retrieving application data

### ISSUE THREAD

**Issue by laureanray** [laureanray/manunugtog#1]
Load and save app last state like:

- current window position (x, y)
- last view (library, now playing)
- last track played + seek time
- window configurations

**Todos**

- [x] add file for saving appdata

- [x] load file when app initialize

- [x] save current app state when exiting

**Comment by laureanray** [comment]
currently working on 5dda8e7801c1e325b11bcdfb0eeb4dc985b607ae
